---
title: "Advanced Modelling - Final Project"
author: "Phong"
date: "2025-03-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(jsonlite)
```

# Data

```{r}
booking_data <- read.csv("data/NDAQ-CHB.csv")
```

Link to dataset: <https://data.nasdaq.com/databases/CHB>

## Data Cleaning

```{r}
booking_data <- booking_data %>% 
  # Initial cleaning
  mutate(across(c(added_date, modified_date, created_date, check_in, check_out, cancel_date), as.Date)) %>% 
  mutate(start_bed_type = gsub(",", "", start_bed_type),
         start_cancel_policy = ifelse(start_cancel_policy == "6 Or More Days Before Checkin", "6 or More Days Before Checkin", start_cancel_policy)) 
```

## Feature Engineering

### Feature Creation

```{r}
data <- booking_data %>% 
  mutate(free_wifi = ifelse(grepl("Free Wifi", start_amenities), 1,0),
         free_breakfast = ifelse(grepl("Free Breakfast", start_amenities), 1,0),
         free_parking = ifelse(grepl("Free Breakfast", start_amenities), 1,0),
         concierge = ifelse(grepl("Concierge", start_amenities), 1,0),
         amenities = free_wifi+free_breakfast+free_parking+concierge,
         cancelled = ifelse(!is.na(cancel_date),1,0),
         cancel_after_booking = as.numeric(cancel_date - created_date),
         cancel_before_checkin = as.numeric(check_in - cancel_date),
         leadtime = as.numeric(check_in - created_date)
         checkin_month = month(check_in),
         weekday_booking = mapply(function(x,y) sum(!weekdays(seq(x, y,"days")) %in% c("Saturday", "Sunday")), check_in,check_out),
         weekdend_booking = mapply(function(x,y) sum(weekdays(seq(x, y,"days")) %in% c("Saturday", "Sunday")), check_in,check_out),
         booking_change = ifelse(added_date == modified_date, 0,1),
         ) %>% 
  # Previous cancellation per company (client)
  group_by(company_id) %>% 
  mutate(client_cancellation = sum(cancelled)) %>% 
  ungroup() %>% 
  # Previous cancellation per agency
  group_by(agency_id) %>% 
  mutate(agency_cancellation = sum(cancelled)) %>% 
  ungroup() %>% 
  # Previous cancellation per hotel
  group_by(hotel_brand_name) %>% 
  mutate(hotel_cancellation = sum(cancelled)) %>% 
  ungroup()
```

### Feature Transformation

### Feature Selection

## EDA

# Classification

## Interpretation

## Prediction

# Regression

## Interpretation

## Prediction
